<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>

 <table class="table">
 <tr>
     <th>First Name</th>
     <th>Last Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($details as $detail) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($detail->first_name);?></td>
     <td><?php echo $this->escapeHtml($detail->last_name);?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $detail->id));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $detail->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>